### ISSUE TITLE
Cannot deploy file with UTF-8 BOM

### ISSUE THREAD

**Issue by zooba** [Azure/Azure-MachineLearning-ClientLibrary-Python#18]
The `_get_source` function does not handle encodings well, in particular, it breaks on a UTF-8 BOM even if the rest of the file is ASCII-compatible.

Would be better as:
```python
source = codecs.open(ourfile, 'r', 'utf-8-sig').read().encode('ascii', errors='strict')
```

But it would probably be better overall if the entire code generation used Unicode throughout (probably via a StringIO instance to avoid the concatenation performance penalties, though those aren't generally going to be a big deal here).

**Comment by DinoV** [comment]
We probably need to respect the UTF8 sig as well as support reading the coding header and re-parsing the file with the correct encoding.

**Comment by zooba** [comment]
Here's the code I recently added profiling to handle this. It should apply for 2.7 as well, but we were already using `execfile` so I didn't have to write it.

```python
if sys.version_info[0] >= 3:
    try:
        from tokenize import open as srcopen
    except ImportError:
        from io import TextIOWrapper
        from tokenize import detect_encoding

        def srcopen(filename):
            buff = open(filename, 'rb')
            try:
                encoding, lines = detect_encoding(buff.readline)
                buff.seek(0)
                if encoding == 'utf-8':
                    if next(iter(buff.read(1)), -1) == 0xEF:
                        encoding = 'utf-8-sig'
                    buff.seek(0)
                stream = TextIOWrapper(buff, encoding, line_buffering=True)
                stream.mode = 'r'
                return stream
            except:
                buff.close()
                raise
```
