### ISSUE TITLE
Inspecting the DOM in IE

### ISSUE THREAD

**Issue by piccolbo** [Azure/Azure-MachineLearning-ClientLibrary-Python#7]
I read in the tests readme:
"You'll need the experiment id (appears in URL), the node id (can be found in the HTML DOM), the port name (displayed as a tooltip when you hover on the output port) and the data type id."

Could you please explain more in detail how to inspect the DOM in IE and where to look exactly for that information?

**Comment by huguesv** [comment]
We now have functionality in Studio that gives you a Python code snippet for intermediate datasets (remember to use a Convert to CSV/TSV module).  That's actually much easier than looking at the HTML DOM.  We should update the test instructions with that :)

In your experiment, click on the output node,  select Generate Data Access Code, and it will give you the code that includes the experiment id, node id, node port.

**Comment by piccolbo** [comment]
Thanks I found out also from the blog about azure and python.
